### ISSUE TITLE
`error: No 'build.zig' file found, in the current directory or any parent directories.`

### ISSUE THREAD

**Issue by Apromixately** [so-dang-cool/dt#13]
I installed on OSX by downloading and installing zig and cloning the v1.0.0 branch and running `./build compile` and `./build test`. I already had Rust.

`zig` seems to run fine.
Running `dt` from the source folder works after an additional `brew install rlwrap`.
Running it from somewhere else gives the error in the topic:
```
info: Initialize a 'build.zig' template file with `zig init-lib` or `zig init-exe`,
or see `zig --help` for more options.
error: No 'build.zig' file found, in the current directory or any parent directories.
```

**Comment by booniepepper** [comment]
A mystery! :detective:

**Comment by booniepepper** [comment]
Aha! I understand what's going on.

The `dt` from the source folder is a little helper script for when I'm developing. It's _intended_ to always build and then run the output. That said, it's going to be confusing to people trying to clone and seeing what seems to be a very obvious entry point.

I'll figure out a way to make it less misleading.

**Comment by booniepepper** [comment]
**For now** to unblock, run `./build release` once in the source directory.

From the repository root, instead of `./dt` run `./zig-out/bin/dt`

**Comment by booniepepper** [comment]
This should be more clear in `dt` 1.0.1 now, and point folks to the right place.
