### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by booniepepper** [so-dang-cool/dt#3]
Create issues for each of these:

- [x] #25
- [x] Write a tutorial!
- [x] Flesh out the user guide (Make more issues?)
- [ ] #47
- [x] #17
- [ ] #48

**Comment by dantecatalfamo** [comment]
How many arguments do the functions from the standard library take? Most of the word signatures have the type `( -- )`, but my understanding is that the forth word notation lists the things taken off of the stack before the double dash and then the things added to the stack after the double dash.

**Comment by dantecatalfamo** [comment]
Oh I see they're defined in `src/builtins.zig`, the notation is just missing on the https://dt.plumbing/stdlib.html page

**Comment by booniepepper** [comment]
Thanks for taking a look!

On the subject of stack effects...

I need to make sure it's being rendered well, and also explain the stack effect syntax

Also just generally think through how to represent "do" and friends, which can have arbitrary effects

**Comment by booniepepper** [comment]
Oh... I didn't html-escape elements like `<a>`!

**Comment by booniepepper** [comment]
Taking shape little-by-little at https://dt.plumbing/user-guide/

**Comment by booniepepper** [comment]
I'm pretty good with where the user guide is at now. It's still early but it's enough for someone to make sense of the basics.

Opened issues for the points that were left un-done.
