### ISSUE TITLE
Install link on home page is broken with GitHub pages 404 error

### ISSUE THREAD

**Issue by edhowland** [so-dang-cool/dt#63]
This link on the main page of dt.plumbing (https://dt.plumbing/user-guide/tutorial/install.html) is broken. It worked yesterday. Now you get a 404 error from GitHub pages.

**Comment by booniepepper** [comment]
Yipes!

I changed it intentionally, but didn't preserve the URL. (I'm not sure if mdBook allows me to do this without a reference from the table of contents) Thanks for reporting. Install instructions are here:

https://dt.plumbing/user-guide/install.html

I'll update links

**Comment by booniepepper** [comment]
https://github.com/so-dang-cool/dt.plumbing/commit/814b0ef5558300e8314efb314273e04bdab91fe5
